services:
  vector:
    image: timberio/vector:latest-alpine
    command: --config /etc/vector/vector-cfg/*
    volumes:
      - ./vector-dev-destination.yml:/etc/vector/vector-cfg/vector-dev-destination.yml
      - ./vector-sources.yml:/etc/vector/vector-cfg/vector-sources.yml

  prometheus:
    image: prom/prometheus:v2.30.3
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./dev-prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: