services:
  kwil-gateway:
    container_name: kwil-gateway
    hostname: kwil-gateway
    build:
      context: .
      dockerfile: ./gateway.dockerfile
    ports:
      - "80:8090"
    environment:
      CHAIN_ID: ${CHAIN_ID:?}
      # default to 3 minutes
      READ_TIMEOUT: ${READ_TIMEOUT:-180}
      # comma separated list of backends
      BACKENDS: ${BACKENDS:?}
      SESSION_SECRET: ${SESSION_SECRET:?}
      DOMAIN: https://${DOMAIN:?}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}
      ALLOW_DEPLOY_DB: true
    volumes:
      - type: bind
        # bind the file to the container
        source: ./kgw
        target: /app/kgw
      - type: bind
        source: ./kgw-config.pkl
        target: /app/kgw-config.pkl