services:
  kwil-gateway:
    container_name: kwil-gateway
    hostname: kwil-gateway
    build:
      context: .
      dockerfile: ./gateway.dockerfile
    ports:
      - "80:8090"
    networks:
      - tsn-network
    environment:
      # todo: make a breaking change that removes default for CHAIN_ID
      #       and make it required
      CHAIN_ID: ${CHAIN_ID:-truflation-staging}
      # comma separated list of backends
      BACKENDS: ${BACKENDS:-tsn-db:8080}
      SESSION_SECRET: ${SESSION_SECRET:?}
      DOMAIN: https://${DOMAIN:-localhost}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}
      ALLOW_DEPLOY_DB: true
    volumes:
      - type: bind
        # bind the file to the container
        source: ./kgw
        target: /app/kgw
      - type: bind
        source: ./kgw-config.pkl
        target: /app/kgw-config.pkl

networks:
  tsn-network:
    driver: bridge
    name: tsn-network
    # should already be created by compose.yaml
    external: true