run:
  deadline: 10m

output:
  formats: github-actions,colored-line-number

issues:
  exclude-dirs:
    - deployments/infra/cdk.out
    - vendor

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - staticcheck
    - sqlclosecheck
    - tparallel
    - typecheck
    - unconvert
    - unused