output:
  format: colored-line-number

run:
  skip-dirs:
    - deployments/infra/cdk.out
    - vendor

linters:
  enable-all: false
  enable:
    - errcheck
    - ineffassign
    - unused
    - staticcheck