version: "2"

output:
  formats:
    text:
      path: stdout
      colors: true

linters:
  settings:
    errcheck:
      enable-all: false
  exclusions:
    paths:
      - deployments/infra/cdk.out
      - vendor
  