run:
  deadline: 10m

output:
  formats:
    text:
      path: stdout
      colors: true

linters:
  settings:
    errcheck:
      disable-all: true
  exclusions:
    paths:
      - deployments/infra/cdk.out
      - vendor
  