linters:
  disable:
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    paths:
      - deployments/infra/cdk.out
      - vendor
run:
  build-tags:
    - kwiltest
output:
  formats:
    text:
      path: stdout
      colors: true
version: "2"
