services:
  kwil-postgres:
    image: "kwildb/postgres:16.8-1"
    hostname: kwil-postgres
    shm_size: 2G
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - ${POSTGRES_VOLUME:-data-kwil-postgres}:/var/lib/postgresql/data
    networks:
      - tsn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  tsn-db:
    container_name: tsn-db
    hostname: tsn-db
    image: "tsn-db:local"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
      # For local development, if cache is not supported, please comment the following lines
      cache_from:
        - ${CACHE_FROM:-type=local,src=/tmp/buildx-cache}/tsn-db
      cache_to:
        - ${CACHE_TO:-type=local,dest=/tmp/buildx-cache-new}/tsn-db
      args:
        - CHAIN_ID=${CHAIN_ID:-tsn-local}
    environment:
      CONFIG_PATH: /root/.kwild
      # app.pg-db-host
      KWILD_DB_HOST: kwil-postgres
    ports:
      - "50051:50051"
      - "50151:50151"
      - "8484:8484"
      - "8080:8080"
      - "26656:26656"
      - "26657:26657"
    depends_on:
      kwil-postgres:
        condition: service_healthy
    volumes:
      - ${TSN_VOLUME:-data-tsn-db}:/root/.kwild
    networks:
      - tsn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

networks:
  tsn-network:
    driver: bridge
    name: tsn-network

volumes:
  data-kwil-postgres:
  data-tsn-db: