services:
  kwil-postgres:
    image: "kwildb/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - type: volume
        source: data-kwil-postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - tsn-network

  tsn-conf:
    # this service permits us to use the best approach for configuration:
    # with target = created, the image will generate a new configuration to be used
    # with target = external, it will use the context folder as the configuration
    # at build time it will copy the configuration to the volume
    build:
      # EXTERNAL_CONFIG_PATH is the path to the configuration directory
      # Both EXTERNAL_CONFIG_PATH and CONF_TARGET should be used together for external configuration
      context: .
      args:
        - EXTERNAL_CONFIG_PATH=${EXTERNAL_CONFIG_PATH}
      dockerfile: ./deployments/tsn-config.dockerfile
      target: ${CONF_TARGET:-created}

    volumes:
      - type: volume
        source: data-tsn-db
        target: /root/.kwild

  tsn-db:
    container_name: tsn-db
    hostname: tsn-db
    image: "tsn-db:local"
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
      # For local development, if cache is not supported, please comment the following lines
      cache_from:
        - ${CACHE_FROM:-type=local,src=/tmp/buildx-cache}/tsn-db
      cache_to:
        - ${CACHE_TO:-type=local,dest=/tmp/buildx-cache-new}/tsn-db
    environment:
      # the hostname of the container. It is used to identify the node in the network
      # if they live in different hosts, it should be the hostname of the host
      HOSTNAME: ${HOSTNAME:-tsn-db}
      CONFIG_PATH: /root/.kwild
      DB_HOST: kwil-postgres
      # comma separated list of peers, used for p2p communication
      PERSISTENT_PEERS: ${PERSISTENT_PEERS}
      # external address of the node, used for p2p communication
      EXTERNAL_ADDRESS: ${EXTERNAL_ADDRESS}

    ports:
      - "50051:50051"
      - "50151:50151"
      - "8484:8484"
      - "8080:8080"
      - "26656:26656"
      - "26657:26657"
    depends_on:
      kwil-postgres:
        condition: service_healthy
      tsn-conf:
        condition: service_completed_successfully
    networks:
      - tsn-network
    volumes:
      - type: volume
        source: data-tsn-db
        target: /root/.kwild

  indexer:
    build: ./deployments/indexer
    ports:
      - "1337:1337"
    depends_on:
      - tsn-db
    networks:
      - tsn-network

networks:
  tsn-network:
    driver: bridge
    name: tsn-network

volumes:
  data-kwil-postgres:
  data-tsn-db:
