services:
  kwil-postgres:
    image: "kwildb/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - type: volume
        source: data-kwil-postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - tsn-network

  tsn-db:
    container_name: tsn-db
    hostname: tsn-db
    image: "tsn-db:local"
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
      cache_from:
        - ${CACHE_FROM:-type=local,src=/tmp/buildx-cache}/tsn-db
      cache_to:
        - ${CACHE_TO:-type=local,dest=/tmp/buildx-cache-new}/tsn-db
    ports:
      - "8080:8080"
    depends_on:
      kwil-postgres:
        condition: service_healthy
    networks:
      - tsn-network
    volumes:
      - type: volume
        source: data-tsn-db
        target: /root/.kwild

networks:
  tsn-network:
    driver: bridge
    name: tsn-network

volumes:
  data-kwil-postgres:
  data-tsn-db:
