services:
  kwil-postgres:
    image: "kwildb/postgres:16.8-1"
    hostname: kwil-postgres
    shm_size: 2G
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - ${POSTGRES_VOLUME:-data-kwil-postgres}:/var/lib/postgresql/data
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  tn-db:
    container_name: tn-db
    hostname: tn-db
    image: "ghcr.io/trufnetwork/node:${TN_IMAGE:-local}"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    environment:
      CONFIG_PATH: /root/.kwild
      # app.pg-db-host
      KWILD_DB_HOST: kwil-postgres
      # Optionally supply SETUP_DB_OWNER to override the owner derived from the generated node key
      SETUP_DB_OWNER: ${SETUP_DB_OWNER:-}
      SETUP_CHAIN_ID: ${SETUP_CHAIN_ID:-trufnetwork-dev}
    ports:
      - "50051:50051"
      - "${TN_RPC_PORT:-8484}:8484"
      - "8080:8080"
      - "26656:26656"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8484/api/v1/health" ]
      interval: 1m
      timeout: 10s
      retries: 10
    depends_on:
      kwil-postgres:
        condition: service_healthy
    volumes:
      - ${TN_VOLUME:-data-tn-db}:/root/.kwild
    networks:
      - tn-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

networks:
  tn-network:
    driver: bridge
    name: tn-network

volumes:
  data-kwil-postgres:
  data-tn-db:
