version: "3"

tasks:
  default:
    cmds:
      - task -l

  build:
    desc: Build kwild binary
    cmds:
      - go build -o ./.build/kwild ./cmd/kwild/main.go

  kwild:
    desc: Run kwild server
    cmds:
      - .build/kwild --autogen

  postgres:
    desc: Run a postgres container
    cmds:
      - docker run -d -p 5432:5432 --name kwil-postgres -e "POSTGRES_HOST_AUTH_METHOD=trust" kwildb/postgres:latest

  tools:
    desc: Install tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
      - go install github.com/vektra/mockery/v2@v2.42.1

  mockery:
    desc: Generate mocks
    cmds:
      - mockery --all

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run
