services:
  kwil-gateway:
    container_name: kwil-gateway
    hostname: kwil-gateway
    volumes:
      - type: bind
        # bind the file to the container
        source: ../../.build/kgw
        target: /app/kgw

    build:
      args:
        - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
        - SESSION_SECRET=${SESSION_SECRET:-not_secret}
        - DOMAIN=https://localhost
      dockerfile: dev-gateway.dockerfile
      context: .
    ports:
      - "8090:8090"
    networks:
      - tsn-network

  nginx:
    container_name: nginx
    hostname: nginx
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./default.conf.template
        target: /etc/nginx/templates/default.conf.template
      - type: bind
        source: ./certs
        target: /etc/nginx/certs
    environment:
      - DOMAIN_NAME=localhost
    depends_on:
      - kwil-gateway
    networks:
      - tsn-network


networks:
  tsn-network:
    driver: bridge
    name: tsn-network
    # should already be created by compose.yaml
    external: true