services:
  kwil-gateway:
    container_name: kwil-gateway
    hostname: kwil-gateway
    volumes:
      - type: bind
        source: ../gateway/kgw-config.pkl
        target: /app/kgw-config.pkl

    build:
      context: ../..
      dockerfile: deployments/gateway/gateway.dockerfile

    ports:
      - "8090:8090"
    networks:
      - tn-network
    environment:
      SESSION_SECRET: ${SESSION_SECRET:-not_secret}
      DOMAIN: https://localhost:443
      # to test the dev-network, use the following values:
      # BACKENDS: tn-db-1:8080,tn-db-2:8080
      BACKENDS: ${BACKENDS:-tn-db:8484}
      CHAIN_ID: ${CHAIN_ID:-trufnetwork-dev}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}
      EXPORT_RPC_META_LOG: "true"
      META_LOG_FORMAT: "otel_nested"
      META_LOG_OTEL_PROCESSOR: "batch"
      OTEL_EXPORTER_OTLP_ENDPOINT: "vector:4317"
      META_LOG_OTEL_COLLECTOR_TLS: "false"
      EXTRA_ARGS: "--allow-chain-rpcs"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  nginx:
    container_name: nginx
    hostname: nginx
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./default.conf.template
        target: /etc/nginx/templates/default.conf.template
      - type: bind
        source: ./certs
        target: /etc/nginx/certs
    environment:
      - DOMAIN_NAME=localhost
    depends_on:
      - kwil-gateway
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  vector:
    image: timberio/vector:latest-alpine
    command: --config /etc/vector/vector-cfg/*
    volumes:
      - ./vector-cfg/:/etc/vector/vector-cfg/:ro

    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  prometheus:
    image: prom/prometheus:v2.30.3
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./dev-prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

volumes:
  grafana-storage:

networks:
  tn-network:
    driver: bridge
    name: tn-network
    # should already be created by compose.yaml
    external: true
