# This file is used to configure the prometheus server to scrape metrics from the vector service
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vector'
    static_configs:
      - targets: ['vector:8686']