services:
  # Caddy is an easy way for us to handle preflight requests to enable cors
  indexer-caddy:
    image: "caddy:latest"
    hostname: indexer-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  indexer-postgres:
    image: "postgres:latest"
    restart: unless-stopped
    hostname: indexer-postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=indexer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - ${POSTGRES_VOLUME:-data-indexer}:/var/lib/postgresql/data
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  indexer:
    restart: unless-stopped
    build:
      dockerfile: indexer.dockerfile
      context: .
    environment:
      NODE_RPC_ENDPOINT: ${NODE_RPC_ENDPOINT:?NODE_RPC_ENDPOINT is required}
      KWIL_PG_CONN: ${KWIL_PG_CONN:?KWIL_PG_CONN is required}
      INDEXER_PG_CONN: "postgresql://postgres:postgres@indexer-postgres:5432/indexer?sslmode=disable"
    ports:
      - "1337:1337"
    networks:
      - tn-network
    depends_on:
      indexer-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1337/v0/swagger" ]
      interval: 5s
      retries: 5
      timeout: 5s
    volumes:
      - ${INDEXER_BINARY_PATH:-./kwil-indexer}:/app/kwil-indexer
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

networks:
  tn-network:
    driver: bridge
    name: tn-network
volumes:
  data-indexer: