name: Release

on:
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  build-release:
    name: Build & release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true

      - name: Build for Darwin AMD64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o ./.build/kwild ./cmd/kwild/main.go
          tar -czvf ./.build/kwild_darwin_amd64.tar.gz -C ./.build kwild
          rm -rf ./.build/kwild

      - name: Build for Darwin ARM64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o ./.build/kwild ./cmd/kwild/main.go
          tar -czvf ./.build/kwild_darwin_arm64.tar.gz -C ./.build kwild
          rm -rf ./.build/kwild

      - name: Build for Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./.build/kwild ./cmd/kwild/main.go
          tar -czvf ./.build/kwild_linux_amd64.tar.gz -C ./.build kwild
          rm -rf ./.build/kwild

      - name: Build for Linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build -o ./.build/kwild ./cmd/kwild/main.go
          tar -czvf ./.build/kwild_linux_arm64.tar.gz -C ./.build kwild
          rm -rf ./.build/kwild

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./.build/kwild_darwin_amd64.tar.gz
            ./.build/kwild_darwin_arm64.tar.gz
            ./.build/kwild_linux_amd64.tar.gz
            ./.build/kwild_linux_arm64.tar.gz